### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by knev** [RangerMauve/local-first-cyberspace#1]
"The more people are loading your content, the more people are re-sharing it"

A major issue with distributed systems is how to update the system. If you are using dat and users are sharing the archive, how are you going to make updates that are applied to all users how have shared the archive?

**Comment by RangerMauve** [comment]
So, Dat is probably one of the better p2p file transfer protocols for sharing updates.

Whenever the owner of a Dat adds a change to an archive, it will replicate to all their peers, and all of those peers' peers. So update should be almost instant in small networks, and take seconds in large ones.

I'd suggest reading the [Dat documentation](https://docs.datproject.org/) and posting any questions you might have on the [forum](https://dat.discourse.group/) or IRC.

**Comment by knev** [comment]
Perfect! =)))
