### ISSUE TITLE
Leaving some inspiration from the active decentralized front :D

### ISSUE THREAD

**Issue by worldpeaceenginelabs** [RangerMauve/local-first-cyberspace#4]
**Hi there. Hope you doing great.**

**I just met some new awesome people the other day, on Github and in the Gun chat on Gitter, and since then, we talk every day about True P2P concepts, and connecting different stacks.**

**There is [Daniel](https://github.com/draeder) who is into that stuff a lot, as you can see from his stack of repositories, and he just coded [Decentralize](https://github.com/draeder/decentralize)**

**Now Daniel seems to have inspired another guy, lionbattery ([ducksandgoats](https://github.com/ducksandgoats)), who came with this one:**

**_"i forked the agregore browser. gonna make my own changes on top of agregore. we can add decentralize and other packages to it.
https://github.com/ducksandgoats/hybrid-browser"_**

**I leave you our last conversation, because i think it could inspire you a lot, since you seem to be on the decentralize train as much as we are. And maybe you wanna follow up their progress? :)**

This conversation started with mentioning this pdf https://cs.brown.edu/research/pubs/theses/ugrad/2019/romano.joseph.pdf

**Daniel**
You know what's interesting about this is that WASM can talk to browser code (javascript). So you could have something like WASM <-> In-browser Javascript <-> Decentralization stack <-> P2P <-> Decentralization stack <-> In-browser Javascript <-> WASM

**Bo**
sounds like connecting everything available with each other (which is the ideal principle of p2p, IOT)

I dont know if you are into science fiction. But they always talk about stuff like relay stations and emitter.

My thought was, could a client also be a relaystation/emitter at the same time?

for instance, you have (we just imagine) 1000 nodes being already connected to each other without servers. (WebRTC direct, DHT exchange, small files with sdp's saved onto IPFS, every node has 100 other sdp's saved(sorted by lowest latency), for fallback, etc.) (we really just imagine here)

This is 1000 of our machines online on the same network, which builds temporarily a virtual network itself.
Couldn't we connect to this network in some way? Some way manually, which we could automate later?

It reminds me always of Zerotier, which applies a virtual ethernet to the network. (maybe i dont get that right, but the principle of a virtual ethernet adapter is intriguing)
Combine this with what you just wrote. Could WASM <-> In-browser Javascript <-> Decentralization stack <-> P2P <-> Decentralization stack <-> In-browser Javascript <-> WASM achieve this eventually?

The other principle is an emitter. something that sends out a steady signal(like radiation(radio channel)), to find each other. Like a beacon or a public heartbeat maybe?

What helps a lot thinking through stuff like this, is imagining the end result:

Imagine 4 Billion nodes already connected. How would 4 Billion already online nodes, rescue one single node, bring him back to the family?
Or how could one node, catch up to the already 4 Billion online nodes? (doesnt matter how we initialized the first 4 Billion)

Its a "to put the cart before the horse" thought experiment, that could help finding the solution.

I know half of what i just wrote is crap, but my point is the principles behind it.

and like always: not only one of the mentioned solutions, but all of them at once

**Daniel**
Unfortunately, until browsers can listen for incoming traffic without having to make outbound requests to a server first, none of what you're envisioning will ever work
That is the single biggest roadblock to true decentralization

**Bo** (next day)
funny thing. i was googling yesterday for p2p browsers.
had this idea of having a browser that runs from a website. (so browser.com for instance opens another browser, which is p2p)

but i guess, same problem with listening to ports???

then tonight, lionbattery wrote this:

i forked the agregore browser. gonna make my own changes on top of agregore. we can add decentralize and other packages to it.
https://github.com/ducksandgoats/hybrid-browser

I see a few possible concepts here:

1. The world needs a new browser in general, which is not google nor microsoft. there are open-source project leaders negotiating/talking to this corporations. But the decision if the available browsers get p2p support or not, shouldnt be their decision anyway. Its like the corporations standing in the way of p2p. I guess its an interest conflict related to their cloud infrastructure.

2. Lets take lionbatteries idea for instance: What about having a new open-source browser? One which you install on your mobile and/or your pc, and it gives you everything we talking about out of the box?
Possible issue: Chrome is so freaking fast, maybe its hard to attract the mass.

3. But what about this? Lets infect the community of developers, open-source lovers, and all-day users with this: lionbatteries idea + Beaker Browser features (Beaker is built with Chromium and should feel exactly like any other Web browser. The big difference: Beaker can host websites.)

Lets incept the following idea:
-you will get a next-generation browser. its fast as chrome. its secure as...whatever(its an advertising anyway, there is no 100% safe).
-get privacy, and get free from corporations in power, hindering us from evolution
-stop paying for webhosting, cause your browser does that now. every other browser user is now your cloud.
-stop paying for domains. Buy it onetime (unstoppable domains) and you will be good.
-with installing this browser, you will become the internet or future of the internet, continue this list just with everything youve been dreaming off (lets dramatize here like Steve Jobs :D )

4. Number three is awesome and could work out, but lets assume, people dont want to change their browser because of habits (even though stop paying for hosting and domains could be a huge catch for many, opening up the possibilities of web3 could be another huge one for early adopters and futurists)
-all i just wrote in number three, but now its not a browser, but an open-source relay which installs in the background, and which developers can use for their projects. (so the developers would start advertising this piece of software as the new holy grail of web3 bla bla, there would be a killer app someday of some dev, which needs this relay in the background, everybody installing it, because this one devs app is so good, you would install everything)

5. Number three for the one half of the people, number four for the other half 😜😜😜

And last but not least: for the people who dont want to install anything:

we offer developers a hybrid solution. build on the web, but the already established number three and number four, will be our signaling servers.

Baaaaaaaam 😂

I have already a name for this baby: The Trinity Project 🤯 a three fold (haha) concept, which combines p2p browsers, p2p relay running as a service, and web-based p2p on the basis of the other two (for the nay sayers)

Just by saying this, it popped in my head: we could inspire others to pop out their own p2p browser/relays(defining some standards or integrate existing ones), so we get choice on the market, which elavates the development/evolution of the whole movement.

And if we standardize this properly, we could also use the "competitors" browsers and relays for signaling. (and they ours of course)

**Daniel**
Lionbattery hit me up.. I could see my library Millimeter turned into that fork with Decentralize built in
I have some other ideas too

**Bo**
yeahhh!!! very cool!!!

**Comment by worldpeaceenginelabs** [comment]
I bundled a Starter Kit with Decentralized, which i am sure, the readme will inspire you too.
https://github.com/worldpeaceenginelabs/P2P-PWA-JAMStack-Starter-Kit-with-Cesium
(PS: i am not sticking to the sequence or priorities, or WebRTC/Gun first/last/main whatever, described in the [True P2P CLIENT CONCEPT](https://github.com/worldpeaceenginelabs/P2P-PWA-JAMStack-Starter-Kit-with-Cesium#true-p2p-client-concept))

**Mostly i want to make a point, connecting already existing decentralization stacks, and the newest, most future-proof stacks in general (basically just by connecting/combining already existing repos from github, there are hundreds of working p2p repos already)**

I have to say that maybe some stuff sound like crap :D due too me, being a very new coder, missing the experience.
But i read code of different languages since i can think, and i am into abstract concepts and math a lot, and Daniel even said, "it doesnt mind at all, because we need fresh ideas in the decentralize realm."

And last, i leave you my personal main project, the Cloud Atlas, which readme you sure will love ;D
https://github.com/worldpeaceenginelabs/CLOUD-ATLAS

Kind regards

Bo

**Comment by worldpeaceenginelabs** [comment]
i just had an idea how to spread (kickstart) the open-source relays to a really huge bunch of people, with just one smart move:

We could team up with Wikipedia and their billion daily users.

Just by having the exact same version of our relay, but a percentage is dedicated to Wikipedias P2P network (there are a few community-developed ones, we could just infect them all with the Trinity Project)

The result: Everybody who wants to support the decentralization of Wikipedia only, downloads their p2p app(our relay) and in turn supports us with being a relay for the whole global true P2P network (which is public and free of course)

**Comment by worldpeaceenginelabs** [comment]
I read you are into ad-hoc.
Leave you this https://berty.tech/blog/bluetooth-low-energy/

And cant wait to see LoRa in mobiles. It would allow P2P Metropolitan networks without any central authority.

Because its not a highspeed connection(like bluetooth and directwifi neither), but has a high range, its ideal for exchanging DHTs and SDPs (a constantly updating list of addresses back into the swarm)(or even just http addresses with such up to date lists would work)

This is why i say: "If you ever thought about how the Evernet will look. It seems like, it is an ever-fallback-net."

Could also imagine a PWA or native app on a mobile (which gives your app the offline ability, with PWA even from the browser) and just updating content via LoRaWa. Combined with voluntary (and/or one gets paid crypto, like helium) LoRa Relay Hotspots, that would hit a lot too.

Imagine a group of 10 volunteers roaming the area for injured people. Catastrophe. No internet at all.
Whatsapp and updated data in the volunteers mission app? Zero problem.

Or a temporary social network on a days long festival
Or a night-long temporary social network on a night club

Kids at schools and sportclubs could have their own local social networks (free from teachers authority and free from predators as a positive side-effect)

Homeless people could have their own social networks.

**Comment by RangerMauve** [comment]
Thank you for the interesting insights! It'll be exciting to see where some of these initiatives go. :)

I've been hard at work the past few months working on Agregore Mobile and reworking a bunch of the internals of Agregore Desktop so I've just gotten around to looking into this now.

One of the reasons I structured Agregore with having `*-fetch` JS APIs as the underlying protocol handlers was so that we could get regular web apps to participate in these p2p swarms too, exactly so that we could support folks that don't want to install a custom browser. Glad to see other folks are interested in similar concepts. :)

I'm gonna close this issue for now since I'm not sure if there's anything actionable to do with it open, but I appreciate you opening it. 🎉

**Comment by worldpeaceenginelabs** [comment]
just as i said, i liked to inspire you, because you inspire us too.

Have a great day.
